apiVersion: v1
kind: Pod
metadata:
  name: standalone-test
  labels:
    tag: standalone-test
spec:
  volumes:
      - name: testalone-pv-storage
        hostPath:
          path: /run/desktop/mnt/host/c/Users/david/PycharmProjects/AutomatizacionGymMunicipales
      - name: dshm
        emptyDir:
          medium: Memory
  containers:
    - name: robotframework-brm
      image: davidcorreas/robot-selenium
      command: ["robot"]
      args: ["-d", "results", 
            "-v", "IS_REMOTE:True",
            "/test/CogerCita.robot"]
      workingDir: /test
      env:
        - name: TZ
          value: "Europe/Madrid"
      volumeMounts:
        - mountPath: "/test"
          name: testalone-pv-storage
      resources:
        limits:
          memory: "1G"
          cpu: "500m"
    - name: standalone-chrome
      image: selenium/standalone-chrome
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      resources:
        limits:
          memory: "2000Mi"
          cpu: "500m"
      ports:
        - containerPort: 4444
        - containerPort: 7900
