on:
  schedule:
    - cron: '15 8 * * 1,3'
    - cron: '15 8 * * 2,4'
  workflow_dispatch:
    inputs:
      relative_day:
        description: 'Day (today, tomorrow, x days later)'
        required: true
        default: '2 days later'
      hour:
        description: 'Hour (0-23)'
        required: true
        default: '9:00'

jobs:
  coger_cita:
    runs-on: self-hosted
    steps:
      - name: Variables
        if: github.event.inputs.relative_day == '' || github.event.inputs.relative_day == ''
        run: |
          echo "RELATIVE_DAY=2 days later" >> $GITHUB_ENV
          echo "HOUR=9:00" >> $GITHUB_ENV
          
      - name: Checkout
        uses: actions/checkout@v2

      # Deploy pod with secrets
      - name: Deploy pod
        env:
          USER_GYM: ${{ secrets.USER_GYM }}
          PASS: ${{ secrets.PASS }}
          NAME: ${{ secrets.NAME }}
          SURNAME: ${{ secrets.SURNAME }}
          RELATIVE_DAY: ${{ github.event.inputs.relative_day || env.RELATIVE_DAY }}
          HOUR: ${{ github.event.inputs.hour || env.HOUR }}
        run: |
          kubectl apply -f deployments/testalone-pods.yaml
      